// The 58 canonical R0 routes (R0-A sección 12). One entry per route; the
// Next.js filesystem in apps/web and apps/control is the real router. A test
// (packages/domain/src/routes/route-registry.test.ts + apps/web/apps/control
// filesystem checks) verifies registry <-> filesystem parity.
import type { ActorRole, RouteEntry } from "./types";

const R0C = "R0-C: identidad, tenancy y capacidades efectivas";
const R0D = "R0-D: vertical de frenos y autorización real";
const R0E = "R0-E: hardening y cierre verificable";
const R1 = "R1: catálogo y ejecución comercial";

const publicRoutes: RouteEntry[] = [
  {
    id: "public.home",
    surface: "public",
    label: "Inicio",
    path: "/",
    icon: "Home",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.home.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek"],
  },
  {
    id: "public.pro",
    surface: "public",
    label: "Datatek Pro",
    path: "/pro",
    icon: "Wrench",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.pro.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Pro"],
  },
  {
    id: "public.pass",
    surface: "public",
    label: "Datatek Pass",
    path: "/pass",
    icon: "IdCard",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.pass.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Pass"],
  },
  {
    id: "public.market",
    surface: "public",
    label: "Datatek Market",
    path: "/market",
    icon: "Store",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.market.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Market"],
  },
  {
    id: "public.trust",
    surface: "public",
    label: "Confianza",
    path: "/trust",
    icon: "ShieldCheck",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.trust.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Confianza"],
  },
  {
    id: "public.security",
    surface: "public",
    label: "Seguridad",
    path: "/security",
    icon: "Lock",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.security.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Seguridad"],
  },
  {
    id: "public.for-workshops",
    surface: "public",
    label: "Para talleres",
    path: "/for-workshops",
    icon: "Building2",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.for-workshops.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Para talleres"],
  },
  {
    id: "public.for-suppliers",
    surface: "public",
    label: "Para proveedores",
    path: "/for-suppliers",
    icon: "Truck",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.for-suppliers.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Para proveedores"],
  },
  {
    id: "public.help",
    surface: "public",
    label: "Ayuda",
    path: "/help",
    icon: "LifeBuoy",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.help.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Ayuda"],
  },
  {
    id: "public.legal.privacy",
    surface: "public",
    label: "Aviso de privacidad",
    path: "/legal/privacy",
    icon: "FileText",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.legal.privacy.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Legal", "Privacidad"],
  },
  {
    id: "public.legal.terms",
    surface: "public",
    label: "Términos",
    path: "/legal/terms",
    icon: "FileText",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.legal.terms.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Legal", "Términos"],
  },
  {
    id: "public.status",
    surface: "public",
    label: "Estado del servicio",
    path: "/status",
    icon: "Activity",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "public.status.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Datatek", "Estado"],
  },
];

const proRoutes: RouteEntry[] = [
  {
    id: "pro.dashboard",
    surface: "pro",
    label: "Inicio",
    path: "/pro/o/[orgSlug]/dashboard",
    icon: "LayoutDashboard",
    release: "r0-b",
    permission: "pro.dashboard.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pro.dashboard.view",
    emptyState: "Sin actividad reciente en esta organización.",
    breadcrumbs: ["Pro", "Inicio"],
  },
  {
    id: "pro.inbox",
    surface: "pro",
    label: "Bandeja",
    path: "/pro/o/[orgSlug]/inbox",
    icon: "Inbox",
    release: "r0-c",
    permission: "pro.inbox.read",
    featureFlag: "pro_inbox",
    navVisible: true,
    telemetry: "pro.inbox.view",
    emptyState: "No hay mensajes pendientes.",
    breadcrumbs: ["Pro", "Bandeja"],
    planned: {
      purpose: "Centralizar solicitudes de Market, mensajes de Pass y alertas operativas.",
      dependency: R0C,
      release: "r0-c",
      dataToBeUsed: "Solicitudes, mensajes y eventos de auditoría por organización.",
      whyDisabled: "Requiere sesión real y aislamiento por organización (RLS).",
    },
  },
  {
    id: "pro.cases",
    surface: "pro",
    label: "Casos",
    path: "/pro/o/[orgSlug]/cases",
    icon: "FolderKanban",
    release: "r0-b",
    permission: "pro.cases.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pro.cases.view",
    emptyState: "Sin casos abiertos todavía.",
    breadcrumbs: ["Pro", "Casos"],
  },
  {
    id: "pro.case-workspace",
    surface: "pro",
    label: "Caso",
    path: "/pro/o/[orgSlug]/cases/[caseId]",
    icon: "FileSearch",
    release: "r0-b",
    permission: "pro.cases.read",
    featureFlag: null,
    navVisible: false,
    telemetry: "pro.case.view",
    emptyState: "Este caso no tiene datos todavía.",
    breadcrumbs: ["Pro", "Casos", "Caso"],
  },
  {
    id: "pro.calendar",
    surface: "pro",
    label: "Agenda",
    path: "/pro/o/[orgSlug]/calendar",
    icon: "CalendarDays",
    release: "r0-d",
    permission: "pro.calendar.read",
    featureFlag: "pro_calendar",
    navVisible: true,
    telemetry: "pro.calendar.view",
    emptyState: "Sin citas programadas.",
    breadcrumbs: ["Pro", "Agenda"],
  },
  {
    id: "pro.shop",
    surface: "pro",
    label: "Taller",
    path: "/pro/o/[orgSlug]/shop",
    icon: "Factory",
    release: "r0-d",
    permission: "pro.shop.read",
    featureFlag: "pro_shop_board",
    navVisible: true,
    telemetry: "pro.shop.view",
    emptyState: "Sin bahías u órdenes activas.",
    breadcrumbs: ["Pro", "Taller"],
    planned: {
      purpose: "Vista operativa de bahías, técnicos y carga de trabajo del día.",
      dependency: R0D,
      release: "r0-d",
      dataToBeUsed: "Casos en progreso, asignaciones y bahías.",
      whyDisabled: "Requiere la vertical de frenos y ejecución real.",
    },
  },
  {
    id: "pro.customers",
    surface: "pro",
    label: "Clientes",
    path: "/pro/o/[orgSlug]/customers",
    icon: "Users",
    release: "r0-c",
    permission: "pro.customers.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pro.customers.view",
    emptyState: "Sin clientes registrados.",
    breadcrumbs: ["Pro", "Clientes"],
  },
  {
    id: "pro.customer-detail",
    surface: "pro",
    label: "Cliente",
    path: "/pro/o/[orgSlug]/customers/[customerId]",
    icon: "User",
    release: "r0-c",
    permission: "pro.customers.read",
    featureFlag: null,
    navVisible: false,
    telemetry: "pro.customer.view",
    emptyState: "Este cliente no tiene historial todavía.",
    breadcrumbs: ["Pro", "Clientes", "Cliente"],
  },
  {
    id: "pro.vehicles",
    surface: "pro",
    label: "Vehículos",
    path: "/pro/o/[orgSlug]/vehicles",
    icon: "Car",
    release: "r0-c",
    permission: "pro.vehicles.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pro.vehicles.view",
    emptyState: "Sin vehículos con acceso concedido.",
    breadcrumbs: ["Pro", "Vehículos"],
  },
  {
    id: "pro.vehicle-detail",
    surface: "pro",
    label: "Vehículo",
    path: "/pro/o/[orgSlug]/vehicles/[vehicleId]",
    icon: "CarFront",
    release: "r0-c",
    permission: "pro.vehicles.read",
    featureFlag: null,
    navVisible: false,
    telemetry: "pro.vehicle.view",
    emptyState: "Sin historial verificable todavía.",
    breadcrumbs: ["Pro", "Vehículos", "Vehículo"],
  },
  {
    id: "pro.parts",
    surface: "pro",
    label: "Repuestos",
    path: "/pro/o/[orgSlug]/parts",
    icon: "PackageSearch",
    release: "r1",
    permission: "pro.parts.read",
    featureFlag: "pro_parts",
    navVisible: true,
    telemetry: "pro.parts.view",
    emptyState: "Sin catálogo de repuestos cargado.",
    breadcrumbs: ["Pro", "Repuestos"],
    planned: {
      purpose: "Catálogo y disponibilidad de repuestos usados en cotizaciones.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Catálogo de repuestos e inventario por organización.",
      whyDisabled: "El inventario queda fuera de alcance de R0.",
    },
  },
  {
    id: "pro.finance",
    surface: "pro",
    label: "Finanzas",
    path: "/pro/o/[orgSlug]/finance",
    icon: "Banknote",
    release: "r1",
    permission: "pro.finance.read",
    featureFlag: "pro_finance",
    navVisible: true,
    telemetry: "pro.finance.view",
    emptyState: "Sin movimientos registrados.",
    breadcrumbs: ["Pro", "Finanzas"],
    planned: {
      purpose: "Cobros, pagos parciales y estado financiero por caso.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Pagos, entregas y facturación por organización.",
      whyDisabled: "Pagos y facturación quedan fuera de alcance de R0.",
    },
  },
  {
    id: "pro.reports",
    surface: "pro",
    label: "Reportes",
    path: "/pro/o/[orgSlug]/reports",
    icon: "ChartBar",
    release: "r0-e",
    permission: "pro.reports.read",
    featureFlag: "pro_reports",
    navVisible: true,
    telemetry: "pro.reports.view",
    emptyState: "Sin datos suficientes para reportar.",
    breadcrumbs: ["Pro", "Reportes"],
    planned: {
      purpose: "KPIs y SLA derivados del mismo alcance de datos que su fuente.",
      dependency: R0E,
      release: "r0-e",
      dataToBeUsed: "Datos analíticos derivados, mismo alcance que la fuente.",
      whyDisabled: "No se usan materialized views ni KPIs inventados en R0-B.",
    },
  },
  {
    id: "pro.loyalty",
    surface: "pro",
    label: "Fidelización",
    path: "/pro/o/[orgSlug]/loyalty",
    icon: "Gift",
    release: "r1",
    permission: "pro.loyalty.read",
    featureFlag: "pro_loyalty",
    navVisible: true,
    telemetry: "pro.loyalty.view",
    emptyState: "Sin programa activo.",
    breadcrumbs: ["Pro", "Fidelización"],
    planned: {
      purpose: "Configurar beneficios de fidelización visibles en Pass.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Reglas de beneficios y saldo por cliente.",
      whyDisabled: "Los puntos nunca compiten con salud/mantenimiento; falta el motor de reglas.",
    },
  },
  {
    id: "pro.settings",
    surface: "pro",
    label: "Configuración",
    path: "/pro/o/[orgSlug]/settings",
    icon: "Settings",
    release: "r0-c",
    permission: "pro.settings.manage",
    featureFlag: null,
    navVisible: true,
    telemetry: "pro.settings.view",
    emptyState: "Sin configuración personalizada todavía.",
    breadcrumbs: ["Pro", "Configuración"],
    planned: {
      purpose: "Organización, sucursales, membresías y capacidades efectivas.",
      dependency: R0C,
      release: "r0-c",
      dataToBeUsed: "Organización, sucursales y membresías.",
      whyDisabled: "Los permisos nacen de membresías reales, no de metadata editable.",
    },
  },
];

const passRoutes: RouteEntry[] = [
  {
    id: "pass.home",
    surface: "pass",
    label: "Inicio",
    path: "/pass",
    icon: "Home",
    release: "r0-b",
    permission: "pass.home.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pass.home.view",
    emptyState: "Todavía no tienes vehículos vinculados.",
    breadcrumbs: ["Pass", "Inicio"],
  },
  {
    id: "pass.garage",
    surface: "pass",
    label: "Garage",
    path: "/pass/garage",
    icon: "Warehouse",
    release: "r0-b",
    permission: "pass.garage.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pass.garage.view",
    emptyState: "Todavía no tienes vehículos vinculados.",
    breadcrumbs: ["Pass", "Garage"],
  },
  {
    id: "pass.vehicle-detail",
    surface: "pass",
    label: "Pasaporte del vehículo",
    path: "/pass/garage/[vehicleId]",
    icon: "IdCard",
    release: "r0-b",
    permission: "pass.garage.read",
    featureFlag: null,
    navVisible: false,
    telemetry: "pass.vehicle.view",
    emptyState: "Sin historial verificable todavía.",
    breadcrumbs: ["Pass", "Garage", "Vehículo"],
  },
  {
    id: "pass.cases",
    surface: "pass",
    label: "Casos",
    path: "/pass/cases",
    icon: "FolderClock",
    release: "r0-b",
    permission: "pass.cases.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pass.cases.view",
    emptyState: "Sin casos por ahora.",
    breadcrumbs: ["Pass", "Casos"],
  },
  {
    id: "pass.case-detail",
    surface: "pass",
    label: "Caso",
    path: "/pass/cases/[caseId]",
    icon: "FileSearch",
    release: "r0-b",
    permission: "pass.cases.read",
    featureFlag: null,
    navVisible: false,
    telemetry: "pass.case.view",
    emptyState: "Este caso no tiene datos todavía.",
    breadcrumbs: ["Pass", "Casos", "Caso"],
  },
  {
    id: "pass.appointments",
    surface: "pass",
    label: "Citas",
    path: "/pass/appointments",
    icon: "CalendarDays",
    release: "r0-d",
    permission: "pass.appointments.read",
    featureFlag: "pass_appointments",
    navVisible: true,
    telemetry: "pass.appointments.view",
    emptyState: "Sin citas programadas.",
    breadcrumbs: ["Pass", "Citas"],
    planned: {
      purpose: "Ver y solicitar citas sin sustituir el expediente del caso.",
      dependency: R0D,
      release: "r0-d",
      dataToBeUsed: "Citas confirmadas y disponibilidad publicada por el taller.",
      whyDisabled: "La agenda funcional queda fuera de alcance de R0-B.",
    },
  },
  {
    id: "pass.benefits",
    surface: "pass",
    label: "Beneficios",
    path: "/pass/benefits",
    icon: "Gift",
    release: "r1",
    permission: "pass.benefits.read",
    featureFlag: "pass_benefits",
    navVisible: true,
    telemetry: "pass.benefits.view",
    emptyState: "Sin beneficios activos.",
    breadcrumbs: ["Pass", "Beneficios"],
    planned: {
      purpose: "Mostrar beneficios y puntos sin competir con salud/mantenimiento.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Saldo y reglas de beneficios por cliente.",
      whyDisabled: "El motor de fidelización todavía no existe.",
    },
  },
  {
    id: "pass.account",
    surface: "pass",
    label: "Cuenta",
    path: "/pass/account",
    icon: "UserCog",
    release: "r0-c",
    permission: "pass.account.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "pass.account.view",
    emptyState: "Sin datos de cuenta todavía.",
    breadcrumbs: ["Pass", "Cuenta"],
    planned: {
      purpose: "Gestionar identidad, verificación y vínculos de cuenta reales.",
      dependency: R0C,
      release: "r0-c",
      dataToBeUsed: "Perfil de usuario y `customer_auth_links`.",
      whyDisabled: "R0-B no implementa login real.",
    },
  },
  {
    id: "limited-auth.token",
    surface: "limited-auth",
    label: "Enlace de autorización",
    path: "/a/[token]",
    icon: "Link",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: false,
    telemetry: "limited_auth.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Enlace de autorización"],
  },
];

const marketRoutes: RouteEntry[] = [
  {
    id: "market.home",
    surface: "market",
    label: "Inicio",
    path: "/market",
    icon: "Store",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "market.home.view",
    emptyState: "Sin talleres demostrativos disponibles.",
    breadcrumbs: ["Market", "Inicio"],
  },
  {
    id: "market.workshops",
    surface: "market",
    label: "Talleres",
    path: "/market/workshops",
    icon: "Building2",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: true,
    telemetry: "market.workshops.view",
    emptyState: "Sin talleres demostrativos disponibles.",
    breadcrumbs: ["Market", "Talleres"],
  },
  {
    id: "market.workshop-detail",
    surface: "market",
    label: "Perfil de taller",
    path: "/market/workshops/[slug]",
    icon: "Building",
    release: "r0-b",
    permission: null,
    featureFlag: null,
    navVisible: false,
    telemetry: "market.workshop.view",
    emptyState: "Este taller no tiene servicios publicados todavía.",
    breadcrumbs: ["Market", "Talleres", "Perfil"],
  },
  {
    id: "market.request",
    surface: "market",
    label: "Nueva solicitud",
    path: "/market/request",
    icon: "SendHorizontal",
    release: "r0-d",
    permission: "market.request.create",
    featureFlag: "market_requests",
    navVisible: true,
    telemetry: "market.request.view",
    emptyState: "No aplica.",
    breadcrumbs: ["Market", "Nueva solicitud"],
    planned: {
      purpose: "Originar una solicitud de servicio sin modificar el expediente operativo.",
      dependency: R0D,
      release: "r0-d",
      dataToBeUsed: "Datos del vehículo y necesidad declarada por el conductor.",
      whyDisabled: "Escribir solicitudes reales queda fuera de alcance de R0-B.",
    },
  },
  {
    id: "market.requests",
    surface: "market",
    label: "Mis solicitudes",
    path: "/market/requests",
    icon: "ListChecks",
    release: "r0-d",
    permission: "market.requests.read",
    featureFlag: "market_requests",
    navVisible: true,
    telemetry: "market.requests.view",
    emptyState: "Sin solicitudes todavía.",
    breadcrumbs: ["Market", "Mis solicitudes"],
    planned: {
      purpose: "Seguimiento de solicitudes originadas en Market.",
      dependency: R0D,
      release: "r0-d",
      dataToBeUsed: "Solicitudes y su estado de atención por taller.",
      whyDisabled: "Depende de la creación real de solicitudes.",
    },
  },
  {
    id: "market.supplier.opportunities",
    surface: "market",
    label: "Oportunidades",
    path: "/market/supplier/opportunities",
    icon: "Radar",
    release: "r1",
    permission: "market.supplier.read",
    featureFlag: "market_supplier",
    navVisible: true,
    telemetry: "market.supplier.opportunities.view",
    emptyState: "Sin oportunidades publicadas.",
    breadcrumbs: ["Market", "Proveedor", "Oportunidades"],
    hiddenForRoles: ["conductor"],
    planned: {
      purpose: "Oportunidades de suministro visibles para proveedores de repuestos.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Solicitudes de repuestos publicadas por talleres.",
      whyDisabled: "El flujo de proveedores queda fuera de alcance de R0.",
    },
  },
  {
    id: "market.supplier.offers",
    surface: "market",
    label: "Ofertas",
    path: "/market/supplier/offers",
    icon: "Tags",
    release: "r1",
    permission: "market.supplier.read",
    featureFlag: "market_supplier",
    navVisible: true,
    telemetry: "market.supplier.offers.view",
    emptyState: "Sin ofertas enviadas.",
    breadcrumbs: ["Market", "Proveedor", "Ofertas"],
    hiddenForRoles: ["conductor"],
    planned: {
      purpose: "Ofertas enviadas por el proveedor a oportunidades abiertas.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Ofertas y su estado de aceptación.",
      whyDisabled: "El flujo de proveedores queda fuera de alcance de R0.",
    },
  },
  {
    id: "market.supplier.orders",
    surface: "market",
    label: "Órdenes",
    path: "/market/supplier/orders",
    icon: "PackageCheck",
    release: "r1",
    permission: "market.supplier.read",
    featureFlag: "market_supplier",
    navVisible: true,
    telemetry: "market.supplier.orders.view",
    emptyState: "Sin órdenes confirmadas.",
    breadcrumbs: ["Market", "Proveedor", "Órdenes"],
    hiddenForRoles: ["conductor"],
    planned: {
      purpose: "Órdenes de suministro confirmadas con un taller.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Órdenes, cantidades y estado de entrega.",
      whyDisabled: "El flujo de proveedores queda fuera de alcance de R0.",
    },
  },
  {
    id: "market.account",
    surface: "market",
    label: "Cuenta",
    path: "/market/account",
    icon: "UserCog",
    release: "r0-c",
    permission: "market.account.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "market.account.view",
    emptyState: "Sin datos de cuenta todavía.",
    breadcrumbs: ["Market", "Cuenta"],
    planned: {
      purpose: "Gestionar identidad real de la cuenta de Market.",
      dependency: R0C,
      release: "r0-c",
      dataToBeUsed: "Perfil de usuario y rol declarado.",
      whyDisabled: "R0-B no implementa login real.",
    },
  },
];

const controlRoutes: RouteEntry[] = [
  {
    id: "control.home",
    surface: "control",
    label: "Inicio",
    path: "/",
    icon: "LayoutDashboard",
    release: "r0-b",
    permission: "control.home.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.home.view",
    emptyState: "Sin señales operativas todavía.",
    breadcrumbs: ["Control", "Inicio"],
  },
  {
    id: "control.status",
    surface: "control",
    label: "Estado de plataforma",
    path: "/status",
    icon: "Activity",
    release: "r0-b",
    permission: "control.status.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.status.view",
    emptyState: "Sin verificaciones registradas.",
    breadcrumbs: ["Control", "Estado"],
  },
  {
    id: "control.organizations",
    surface: "control",
    label: "Organizaciones",
    path: "/organizations",
    icon: "Building2",
    release: "r0-c",
    permission: "control.organizations.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.organizations.view",
    emptyState: "Sin organizaciones registradas.",
    breadcrumbs: ["Control", "Organizaciones"],
  },
  {
    id: "control.organization-detail",
    surface: "control",
    label: "Organización",
    path: "/organizations/[organizationId]",
    icon: "Building",
    release: "r0-c",
    permission: "control.organizations.read",
    featureFlag: null,
    navVisible: false,
    telemetry: "control.organization.view",
    emptyState: "Sin datos todavía.",
    breadcrumbs: ["Control", "Organizaciones", "Organización"],
  },
  {
    id: "control.users",
    surface: "control",
    label: "Usuarios",
    path: "/users",
    icon: "Users",
    release: "r0-c",
    permission: "control.users.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.users.view",
    emptyState: "Sin usuarios de plataforma registrados.",
    breadcrumbs: ["Control", "Usuarios"],
  },
  {
    id: "control.catalog",
    surface: "control",
    label: "Catálogo",
    path: "/catalog",
    icon: "BookOpen",
    release: "r1",
    permission: "control.catalog.manage",
    featureFlag: "control_catalog",
    navVisible: true,
    telemetry: "control.catalog.view",
    emptyState: "Sin catálogo publicado.",
    breadcrumbs: ["Control", "Catálogo"],
    planned: {
      purpose: "Gobernar el catálogo comercial compartido entre organizaciones.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Catálogo de servicios y repuestos de referencia.",
      whyDisabled: "El dominio comercial final queda diferido a R1.",
    },
  },
  {
    id: "control.support",
    surface: "control",
    label: "Soporte",
    path: "/support",
    icon: "Headset",
    release: "r0-c",
    permission: "control.support.elevated",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.support.view",
    emptyState: "Sin casos de soporte abiertos.",
    breadcrumbs: ["Control", "Soporte"],
  },
  {
    id: "control.disputes",
    surface: "control",
    label: "Disputas",
    path: "/disputes",
    icon: "Gavel",
    release: "r1",
    permission: "control.disputes.manage",
    featureFlag: "control_disputes",
    navVisible: true,
    telemetry: "control.disputes.view",
    emptyState: "Sin disputas abiertas.",
    breadcrumbs: ["Control", "Disputas"],
    planned: {
      purpose: "Gestionar disputas entre organizaciones, clientes y proveedores.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Casos en disputa y su historial de resolución.",
      whyDisabled: "La política final de disputas está diferida.",
    },
  },
  {
    id: "control.security",
    surface: "control",
    label: "Seguridad",
    path: "/security",
    icon: "ShieldAlert",
    release: "r0-e",
    permission: "control.security.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.security.view",
    emptyState: "Sin incidentes registrados.",
    breadcrumbs: ["Control", "Seguridad"],
    planned: {
      purpose: "Panel de incidentes, fraude y auditoría global de la plataforma.",
      dependency: R0E,
      release: "r0-e",
      dataToBeUsed: "Eventos de auditoría append-only y alertas de seguridad.",
      whyDisabled: "El hardening y cierre verificable todavía no corrió.",
    },
  },
  {
    id: "control.integrations",
    surface: "control",
    label: "Integraciones",
    path: "/integrations",
    icon: "Plug",
    release: "r1",
    permission: "control.integrations.manage",
    featureFlag: "control_integrations",
    navVisible: true,
    telemetry: "control.integrations.view",
    emptyState: "Sin integraciones configuradas.",
    breadcrumbs: ["Control", "Integraciones"],
    planned: {
      purpose: "Configurar proveedores de WhatsApp, correo y monitoreo detrás de adaptadores.",
      dependency: R1,
      release: "r1",
      dataToBeUsed: "Credenciales de integración, nunca en el navegador.",
      whyDisabled: "Los proveedores externos están explícitamente diferidos en R0-A.",
    },
  },
  {
    id: "control.feature-flags",
    surface: "control",
    label: "Feature flags",
    path: "/feature-flags",
    icon: "ToggleLeft",
    release: "r0-c",
    permission: "control.feature_flags.manage",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.feature_flags.view",
    emptyState: "Sin feature flags registrados.",
    breadcrumbs: ["Control", "Feature flags"],
    planned: {
      purpose: "Activar/desactivar features por organización sin tocar código.",
      dependency: R0C,
      release: "r0-c",
      dataToBeUsed: "Registro de feature flags y su alcance.",
      whyDisabled: "Requiere backend real de configuración; hoy es metadata estática.",
    },
  },
  {
    id: "control.audit",
    surface: "control",
    label: "Auditoría",
    path: "/audit",
    icon: "ScrollText",
    release: "r0-e",
    permission: "control.audit.read",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.audit.view",
    emptyState: "Sin eventos de auditoría todavía.",
    breadcrumbs: ["Control", "Auditoría"],
    planned: {
      purpose: "Consultar el registro append-only de eventos sensibles.",
      dependency: R0E,
      release: "r0-e",
      dataToBeUsed: "Eventos de auditoría append-only por organización y plataforma.",
      whyDisabled: "No existen mutaciones reales todavía; no hay eventos que auditar.",
    },
  },
  {
    id: "control.settings",
    surface: "control",
    label: "Configuración",
    path: "/settings",
    icon: "Settings",
    release: "r0-c",
    permission: "control.settings.manage",
    featureFlag: null,
    navVisible: true,
    telemetry: "control.settings.view",
    emptyState: "Sin configuración personalizada todavía.",
    breadcrumbs: ["Control", "Configuración"],
    planned: {
      purpose: "Configuración global de la plataforma y roles de Control.",
      dependency: R0C,
      release: "r0-c",
      dataToBeUsed: "Configuración de plataforma y roles separados de organización.",
      whyDisabled: "Requiere identidad real separada de la sesión pública.",
    },
  },
];

export const ROUTE_REGISTRY: RouteEntry[] = [
  ...publicRoutes,
  ...proRoutes,
  ...passRoutes,
  ...marketRoutes,
  ...controlRoutes,
];

export function findRouteById(id: string): RouteEntry | undefined {
  return ROUTE_REGISTRY.find((r) => r.id === id);
}

export function routesForSurface(surface: RouteEntry["surface"]): RouteEntry[] {
  return ROUTE_REGISTRY.filter((r) => r.surface === surface);
}

export function isHiddenForRole(route: RouteEntry, role: ActorRole): boolean {
  return route.hiddenForRoles?.includes(role) ?? false;
}
